### ISSUE TITLE
Website Hosting (GitHub Pages)

### ISSUE THREAD

**Issue by 392781** [UCSB-PSTAT/computing-backup#3]
Relevant link: https://medium.com/superhighfives/deploying-to-github-pages-with-gulp-c06efc527de8

**Comment by 392781** [comment]
Currently at a standstill.  There are issues hosting the webpages as all the CSS linking doesn't seem to work.  In addition, the development of googlecolab/tools seems to have stopped (many services and toolchains are deprecated.  Website is currently building but unpublishable).

**Comment by syoh** [comment]
I put an offline process for building pages and serving through github pages: https://github.com/UCSB-PSTAT/wiki/blob/build-pages/wiki_pages.md

The current set of codelabs are served under these URLS
- https://ucsb-pstat.github.io/wiki/ssh-setup
- https://ucsb-pstat.github.io/wiki/devcontainer-setup
- https://ucsb-pstat.github.io/wiki/local-devcontainers

**Comment by 392781** [comment]
Oh I see.  I'll try to replicate something similar for the landing page.  What I meant by the previous comment was that there is a weird issue with the original tools way of hosting the main page that is causing issues (none of the CSS showing up).

I think I've lost the forest for the trees so to speak.  I'll try again with your set up in mind.

**Comment by 392781** [comment]
@syoh by the way, this is a potential long term solution for documentation management that could be considered down the line: https://docusaurus.io/

On the development end, it's all markdown based with easy static hosting.  It is also actively maintained.

On the user end, it replicates similar elements to codelabs (if customized with that in mind).

**Comment by 392781** [comment]
Completed with #4
