### ISSUE TITLE
CNAME and website customization

### ISSUE THREAD

**Issue by 392781** [UCSB-PSTAT/computing-backup#5]
Requires:
* CNAME entry for computing.pstat.ucsb.edu
* Entries added on home page via `index.md`
* brands.ucsb.edu
  * favicon
  * department logo + department title
  * custom CSS for jekyll
  * OpenGraph descriptors + banner

**Comment by syoh** [comment]
What do you think about using this theme? 

https://just-the-docs.com/

Not sure if `minima` theme has them, too. Built-in search and a sidebar could be useful for navigation.

**Comment by 392781** [comment]
I agree, I think I prefer this to `minima`.  Its more documentation focused and has nicer UI out the box.

**Comment by syoh** [comment]
Sounds good. You can [clone this repo](https://github.com/syoh/zxcv/) and modify `docs/_config.yml`
